server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: Delpiero10
    url: jdbc:postgresql://localhost:5432/pantry
    username: soufiane
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gergohuber@gmail.com
    password: password

    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        debug: true